# This workflow calls the main distribution pipeline from DuckDB to build and
# test the extension.
name: Main extension distribution pipeline
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true
jobs:
  duckdb-stable-build:
    name: Build extension binaries (DuckDB v1.4.3)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4.3
    with:
      duckdb_version: v1.4.3
      ci_tools_version: v1.4.3
      extension_name: elasticsearch
  duckdb-next-build:
    name: Build extension binaries (DuckDB main)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: elasticsearch
  code-quality-check:
    name: Check code quality
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@v1.4.3
    with:
      duckdb_version: v1.4.3
      ci_tools_version: v1.4.3
      extension_name: elasticsearch
      format_checks: "format;tidy"
